export type ExerciseDefinition = {
  name: string;
  category: "Konkurrenceløft" | "Snatch" | "Clean" | "Jerk" | "Squat" | "Træk" | "Assistance" | "Svømmestyrke" | "Svømning";
  target: string;
  cue: string;
  sets: string;
  reps: string;
  weight: string;
  format?: "load" | "distance";
};

export const exerciseLibrary: ExerciseDefinition[] = [
  { name: "Snatch", category: "Konkurrenceløft", target: "Helkrop · teknik", cue: "Tæt stang og aktiv modtagelse", sets: "5", reps: "2", weight: "60" },
  { name: "Hang snatch", category: "Snatch", target: "Timing · eksplosivitet", cue: "Hold spændingen over knæet", sets: "4", reps: "3", weight: "50" },
  { name: "Power snatch", category: "Snatch", target: "Hastighed · træk", cue: "Modtag stangen højt og stabilt", sets: "5", reps: "2", weight: "55" },
  { name: "Snatch balance", category: "Snatch", target: "Modtagelse · fodarbejde", cue: "Pres aktivt op mod stangen", sets: "4", reps: "3", weight: "45" },
  { name: "Clean & Jerk", category: "Konkurrenceløft", target: "Helkrop · teknik", cue: "Stabil clean før et roligt dip", sets: "5", reps: "1+1", weight: "80" },
  { name: "Hang clean", category: "Clean", target: "Position · turnover", cue: "Afslut benene før albuerne", sets: "4", reps: "3", weight: "70" },
  { name: "Power clean", category: "Clean", target: "Eksplosivitet · hastighed", cue: "Mød stangen – lad den ikke falde", sets: "5", reps: "2", weight: "75" },
  { name: "Push jerk", category: "Jerk", target: "Ben-drive · timing", cue: "Lodret dip og hurtig lockout", sets: "5", reps: "3", weight: "70" },
  { name: "Front squat", category: "Squat", target: "Ben · core", cue: "Albuer højt gennem hele løftet", sets: "4", reps: "4", weight: "90" },
  { name: "Back squat", category: "Squat", target: "Maksimal benstyrke", cue: "Stabil bracing og ensartet dybde", sets: "5", reps: "5", weight: "110" },
  { name: "Snatch pull", category: "Træk", target: "Ryg · position · kraft", cue: "Bevar skuldrene over stangen", sets: "4", reps: "3", weight: "80" },
  { name: "Clean pull", category: "Træk", target: "Ben · ryg · kraft", cue: "Skub gulvet væk og afslut lodret", sets: "4", reps: "3", weight: "110" },
  { name: "Strict press", category: "Assistance", target: "Skuldre · lockout", cue: "Spænd balder og hold ribben nede", sets: "4", reps: "6", weight: "40" },
  { name: "High hang snatch", category: "Snatch", target: "Timing · hurtighed", cue: "Bliv lodret og angrib under stangen", sets: "5", reps: "2", weight: "45" },
  { name: "Low hang snatch", category: "Snatch", target: "Position · tålmodighed", cue: "Hold rygvinklen til stangen passerer knæet", sets: "4", reps: "3", weight: "50" },
  { name: "Block snatch", category: "Snatch", target: "Eksplosivitet · position", cue: "Skab tryk før du accelererer", sets: "5", reps: "2", weight: "55" },
  { name: "Deficit snatch", category: "Snatch", target: "Startstyrke · ben", cue: "Pres gulvet væk uden at løfte hoften tidligt", sets: "4", reps: "2", weight: "50" },
  { name: "Pause snatch", category: "Snatch", target: "Kontrol · position", cue: "Frys positionen og behold balancen midt på foden", sets: "5", reps: "2", weight: "50" },
  { name: "No-foot snatch", category: "Snatch", target: "Balance · vertikal kraft", cue: "Stræk lodret uden at hoppe frem", sets: "4", reps: "3", weight: "45" },
  { name: "No-hook snatch", category: "Snatch", target: "Afslappede arme · timing", cue: "Lad benene drive løftet", sets: "4", reps: "3", weight: "40" },
  { name: "Muscle snatch", category: "Snatch", target: "Turnover · overkrop", cue: "Hold stangen tæt og afslut med aktive skuldre", sets: "4", reps: "4", weight: "35" },
  { name: "Tall snatch", category: "Snatch", target: "Turnover · hastighed", cue: "Træk dig direkte under stangen", sets: "4", reps: "3", weight: "30" },
  { name: "Snatch from power position", category: "Snatch", target: "Kontakt · timing", cue: "Bevar trykket i hele foden før eksplosiv afslutning", sets: "5", reps: "2", weight: "45" },
  { name: "Snatch from knee", category: "Snatch", target: "Knæpassage · position", cue: "Hold stangen tæt gennem knæpassagen", sets: "4", reps: "3", weight: "50" },
  { name: "Snatch from blocks below knee", category: "Snatch", target: "Første træk · position", cue: "Start roligt og accelerér efter knæet", sets: "4", reps: "2", weight: "55" },
  { name: "Snatch from blocks above knee", category: "Snatch", target: "Andet træk · kraft", cue: "Hold brystet over stangen til kontakt", sets: "5", reps: "2", weight: "55" },
  { name: "Power snatch + overhead squat", category: "Snatch", target: "Modtagelse · mobilitet", cue: "Stabilisér før du går kontrolleret ned", sets: "4", reps: "1+2", weight: "45" },
  { name: "Snatch + overhead squat", category: "Snatch", target: "Stabilitet · teknik", cue: "Behold aktive skuldre mellem løftene", sets: "4", reps: "1+1", weight: "50" },
  { name: "Snatch pull + snatch", category: "Snatch", target: "Trækbane · overførsel", cue: "Gentag samme bane i begge bevægelser", sets: "4", reps: "1+1", weight: "50" },
  { name: "Snatch deadlift", category: "Træk", target: "Position · bagkæde", cue: "Hold brystet over stangen og spænd lats", sets: "4", reps: "4", weight: "90" },
  { name: "Snatch grip RDL", category: "Træk", target: "Baglår · ryg", cue: "Skub hoften tilbage med stangen tæt", sets: "4", reps: "6", weight: "70" },
  { name: "Snatch grip push press", category: "Snatch", target: "Overheadstyrke · timing", cue: "Afslut benene og pres stangen lodret", sets: "4", reps: "5", weight: "45" },
  { name: "Overhead squat", category: "Snatch", target: "Mobilitet · stabilitet", cue: "Pres op i stangen og hold hele foden i gulvet", sets: "4", reps: "5", weight: "45" },
  { name: "High hang clean", category: "Clean", target: "Timing · hurtighed", cue: "Bliv høj og mød stangen hurtigt", sets: "5", reps: "2", weight: "65" },
  { name: "Low hang clean", category: "Clean", target: "Position · kraft", cue: "Hold spændingen under knæet", sets: "4", reps: "3", weight: "70" },
  { name: "Block clean", category: "Clean", target: "Eksplosivitet · turnover", cue: "Skab balance før den eksplosive afslutning", sets: "5", reps: "2", weight: "75" },
  { name: "Deficit clean", category: "Clean", target: "Startstyrke · ben", cue: "Pres jævnt gennem gulvet", sets: "4", reps: "2", weight: "70" },
  { name: "Pause clean", category: "Clean", target: "Kontrol · position", cue: "Bevar spændingen i pausen", sets: "5", reps: "2", weight: "70" },
  { name: "No-foot clean", category: "Clean", target: "Balance · vertikal kraft", cue: "Stræk lodret og land samme sted", sets: "4", reps: "3", weight: "65" },
  { name: "No-hook clean", category: "Clean", target: "Timing · afslappede arme", cue: "Hold armene lange gennem trækket", sets: "4", reps: "3", weight: "60" },
  { name: "Muscle clean", category: "Clean", target: "Turnover · albuer", cue: "Før albuerne hurtigt rundt om stangen", sets: "4", reps: "4", weight: "45" },
  { name: "Tall clean", category: "Clean", target: "Turnover · modtagelse", cue: "Træk kroppen hurtigt ned", sets: "4", reps: "3", weight: "40" },
  { name: "Clean from power position", category: "Clean", target: "Kontakt · timing", cue: "Hold balancen og afslut med benene", sets: "5", reps: "2", weight: "65" },
  { name: "Clean from knee", category: "Clean", target: "Knæpassage · position", cue: "Bevar skuldrene over stangen", sets: "4", reps: "3", weight: "70" },
  { name: "Clean from blocks below knee", category: "Clean", target: "Første træk · styrke", cue: "Pres roligt til stangen passerer knæet", sets: "4", reps: "2", weight: "75" },
  { name: "Clean from blocks above knee", category: "Clean", target: "Andet træk · kraft", cue: "Hold stangen tæt ind i kontakten", sets: "5", reps: "2", weight: "75" },
  { name: "Power clean + front squat", category: "Clean", target: "Modtagelse · benstyrke", cue: "Stabilisér før den kontrollerede squat", sets: "4", reps: "1+2", weight: "70" },
  { name: "Clean + front squat", category: "Clean", target: "Benstyrke · position", cue: "Hold albuerne højt mellem bevægelserne", sets: "4", reps: "1+1", weight: "75" },
  { name: "Clean deadlift", category: "Træk", target: "Position · bagkæde", cue: "Pres gulvet væk med brystet over stangen", sets: "4", reps: "4", weight: "120" },
  { name: "Clean grip RDL", category: "Træk", target: "Baglår · ryg", cue: "Hold lats spændte og hoften tilbage", sets: "4", reps: "6", weight: "90" },
  { name: "Split jerk", category: "Jerk", target: "Fodarbejde · lockout", cue: "Flyt fødderne hurtigt og land stabilt", sets: "5", reps: "2", weight: "75" },
  { name: "Power jerk", category: "Jerk", target: "Ben-drive · modtagelse", cue: "Pres dig hurtigt ned under stangen", sets: "5", reps: "2", weight: "70" },
  { name: "Squat jerk", category: "Jerk", target: "Mobilitet · modtagelse", cue: "Hold dip lodret og modtag aktivt", sets: "4", reps: "2", weight: "55" },
  { name: "Push press", category: "Jerk", target: "Ben-drive · skuldre", cue: "Afslut benene før armene", sets: "4", reps: "5", weight: "60" },
  { name: "Behind-the-neck push press", category: "Jerk", target: "Overheadstyrke · lodret bane", cue: "Hold hovedet neutralt og pres lige op", sets: "4", reps: "5", weight: "65" },
  { name: "Behind-the-neck split jerk", category: "Jerk", target: "Fodarbejde · sikkerhed", cue: "Fokusér på hurtig og balanceret landing", sets: "5", reps: "2", weight: "70" },
  { name: "Jerk from rack", category: "Jerk", target: "Teknik · belastning", cue: "Find balancen før hvert dip", sets: "5", reps: "2", weight: "80" },
  { name: "Jerk from blocks", category: "Jerk", target: "Ben-drive · gentagelser", cue: "Nulstil positionen mellem løftene", sets: "5", reps: "2", weight: "80" },
  { name: "Pause jerk", category: "Jerk", target: "Dipkontrol · timing", cue: "Hold trykket midt på foden i pausen", sets: "5", reps: "2", weight: "70" },
  { name: "Tall jerk", category: "Jerk", target: "Fodarbejde · lockout", cue: "Flyt fødderne uden ekstra dip", sets: "4", reps: "3", weight: "40" },
  { name: "Jerk balance", category: "Jerk", target: "Forreste fod · modtagelse", cue: "Træd frem og lås stangen samtidig", sets: "4", reps: "3", weight: "45" },
  { name: "Press in split", category: "Jerk", target: "Stabilitet · lockout", cue: "Hold hofterne under skuldrene", sets: "4", reps: "5", weight: "35" },
  { name: "Dip squat", category: "Jerk", target: "Dipstyrke · position", cue: "Bevar lodret torso og fuld fodkontakt", sets: "4", reps: "5", weight: "100" },
  { name: "Jerk dip + drive", category: "Jerk", target: "Ben-drive · rytme", cue: "Skift hurtigt retning uden at miste balancen", sets: "4", reps: "3", weight: "85" },
  { name: "Clean & push jerk", category: "Jerk", target: "Helkrop · teknik", cue: "Stabilisér clean før et lodret dip", sets: "5", reps: "1+1", weight: "75" },
  { name: "Pause front squat", category: "Squat", target: "Bundstyrke · position", cue: "Bevar spændingen og albuerne højt", sets: "4", reps: "3", weight: "85" },
  { name: "Tempo front squat", category: "Squat", target: "Kontrol · benstyrke", cue: "Brug tre sekunder ned og rejs dig aggressivt", sets: "4", reps: "4", weight: "75" },
  { name: "Pin front squat", category: "Squat", target: "Startstyrke · core", cue: "Start spændt fra en helt stille position", sets: "5", reps: "3", weight: "80" },
  { name: "Front squat + jerk", category: "Squat", target: "Ben · overførsel", cue: "Brug en stabil squat til at sætte jerken op", sets: "4", reps: "2+1", weight: "75" },
  { name: "Pause back squat", category: "Squat", target: "Bundstyrke · kontrol", cue: "Hold spændingen gennem hele pausen", sets: "4", reps: "4", weight: "95" },
  { name: "Tempo back squat", category: "Squat", target: "Kontrol · muskelstyrke", cue: "Kontrollér vejen ned og behold balancen", sets: "4", reps: "5", weight: "90" },
  { name: "High-bar back squat", category: "Squat", target: "Benstyrke · oprejst position", cue: "Hold knæene fremme og brystet højt", sets: "5", reps: "5", weight: "105" },
  { name: "Low-bar back squat", category: "Squat", target: "Bagkæde · maksimal styrke", cue: "Skab en stabil hylde og pres gennem hoften", sets: "5", reps: "5", weight: "120" },
  { name: "Box squat", category: "Squat", target: "Bagkæde · kontrol", cue: "Sæt dig kontrolleret og behold spændingen", sets: "4", reps: "5", weight: "100" },
  { name: "Anderson squat", category: "Squat", target: "Startstyrke · ben", cue: "Byg spænding før stangen forlader pins", sets: "5", reps: "3", weight: "90" },
  { name: "Split squat", category: "Squat", target: "Ensidig benstyrke · balance", cue: "Hold forreste fod stabil og torso høj", sets: "4", reps: "6", weight: "40" },
  { name: "Bulgarian split squat", category: "Squat", target: "Ensidig styrke · stabilitet", cue: "Sænk bageste knæ kontrolleret", sets: "4", reps: "8", weight: "35" },
  { name: "Snatch high pull", category: "Træk", target: "Kraft · albueføring", cue: "Afslut benene før albuerne går op", sets: "4", reps: "4", weight: "75" },
  { name: "Clean high pull", category: "Træk", target: "Kraft · afslutning", cue: "Hold stangen tæt og afslut lodret", sets: "4", reps: "4", weight: "100" },
  { name: "Snatch pull from blocks", category: "Træk", target: "Andet træk · belastning", cue: "Start balanceret og accelerér gennem kontakten", sets: "4", reps: "3", weight: "85" },
  { name: "Clean pull from blocks", category: "Træk", target: "Andet træk · kraft", cue: "Hold skuldrene over stangen længst muligt", sets: "4", reps: "3", weight: "115" },
  { name: "Snatch pull with pause", category: "Træk", target: "Position · kontrol", cue: "Bevar spændingen i pausen ved knæet", sets: "4", reps: "3", weight: "80" },
  { name: "Clean pull with pause", category: "Træk", target: "Position · benstyrke", cue: "Hold hele foden i gulvet under pausen", sets: "4", reps: "3", weight: "110" },
  { name: "Snatch deficit pull", category: "Træk", target: "Startstyrke · position", cue: "Pres jævnt uden at ændre rygvinklen", sets: "4", reps: "3", weight: "75" },
  { name: "Clean deficit pull", category: "Træk", target: "Startstyrke · ben", cue: "Hold brystet over stangen fra gulvet", sets: "4", reps: "3", weight: "105" },
  { name: "Bænkpres", category: "Assistance", target: "Bryst · triceps", cue: "Hold skulderbladene stabile mod bænken", sets: "4", reps: "6", weight: "70" },
  { name: "Pendlay row", category: "Assistance", target: "Øvre ryg · trækstyrke", cue: "Hold ryggen fast og træk mod nederste ribben", sets: "4", reps: "6", weight: "70" },
  { name: "Pull-up", category: "Assistance", target: "Ryg · greb", cue: "Start med aktive skuldre og undgå kip", sets: "4", reps: "6", weight: "0" },
  { name: "Romanian deadlift", category: "Assistance", target: "Baglår · bagkæde", cue: "Skub hoften tilbage med neutral ryg", sets: "4", reps: "8", weight: "90" },
  { name: "Plank", category: "Assistance", target: "Core · stabilitet", cue: "Spænd balder og hold ribben nede", sets: "4", reps: "30", weight: "0" },
  { name: "Lat pulldown", category: "Assistance", target: "Ryg · trækstyrke", cue: "Hold ribben nede og før albuerne mod siden", sets: "4", reps: "8", weight: "45" },
  { name: "Seated cable row", category: "Assistance", target: "Øvre ryg · holdning", cue: "Saml skulderbladene uden at læne dig tilbage", sets: "4", reps: "10", weight: "40" },
  { name: "Push-up", category: "Assistance", target: "Bryst · skulderkontrol", cue: "Bevar en lang kropslinje og lad skulderbladene bevæge sig", sets: "4", reps: "10", weight: "0" },
  { name: "Half-kneeling landmine press", category: "Assistance", target: "Skulder · core", cue: "Hold ribben nede og pres skråt frem", sets: "3", reps: "8", weight: "25" },
  { name: "Pallof press", category: "Assistance", target: "Core · antirotation", cue: "Hold bryst og hofter lige frem", sets: "3", reps: "10", weight: "12" },
  { name: "Dead bug", category: "Assistance", target: "Core · kontrol", cue: "Hold lænden roligt mod gulvet", sets: "3", reps: "10", weight: "0" },
  { name: "Side plank", category: "Assistance", target: "Core · sidestabilitet", cue: "Hold kroppen lang fra hoved til fod", sets: "3", reps: "30 sek", weight: "0" },
  { name: "Copenhagen plank", category: "Assistance", target: "Hofte · core", cue: "Hold bækkenet højt og stabilt", sets: "3", reps: "20 sek", weight: "0" },
  { name: "Bird dog", category: "Assistance", target: "Core · krydsstabilitet", cue: "Undgå rotation mens arm og ben strækkes", sets: "3", reps: "10", weight: "0" },
  { name: "Box jump", category: "Assistance", target: "Ben · eksplosivitet", cue: "Land blødt og stop før springhøjden falder", sets: "5", reps: "3", weight: "0" },
  { name: "Medicine ball slam", category: "Assistance", target: "Helkrop · power", cue: "Skab kraft fra hele kroppen og kast hurtigt", sets: "5", reps: "5", weight: "6" },
  { name: "Band external rotation", category: "Assistance", target: "Rotatorcuff · skulderkontrol", cue: "Hold albuen tæt og brug let modstand", sets: "3", reps: "12", weight: "5" },
  { name: "Calf raise", category: "Assistance", target: "Læg · ankelstyrke", cue: "Arbejd gennem fuldt bevægeudslag", sets: "3", reps: "12", weight: "30" },
  { name: "Single-leg Romanian deadlift", category: "Assistance", target: "Bagkæde · hoftestabilitet", cue: "Hold bækkenet lige og bevæg dig fra hoften", sets: "3", reps: "8", weight: "20" },
  { name: "Dødløft", category: "Assistance", target: "Bagkæde · maksimal styrke", cue: "Spænd op før stangen forlader gulvet, og hold den tæt", sets: "4", reps: "5", weight: "100" },
  { name: "Dips", category: "Assistance", target: "Bryst · triceps · skulderstabilitet", cue: "Hold skuldrene nede og arbejd i et kontrolleret bevægeudslag", sets: "4", reps: "8", weight: "0" },
  { name: "Hip thrust", category: "Assistance", target: "Balder · hofteekstension", cue: "Hold ribbenene nede og afslut med fuld hoftestræk", sets: "4", reps: "8", weight: "80" },
  { name: "Dumbbell shoulder press", category: "Assistance", target: "Skuldre · triceps", cue: "Pres håndvægtene op uden at overstrække lænden", sets: "3", reps: "8", weight: "20" },
  { name: "Farmer's walk", category: "Assistance", target: "Greb · core · holdning", cue: "Gå roligt med høj kropsholdning og stabile skuldre", sets: "4", reps: "30 m", weight: "30" },
  { name: "Face pull", category: "Assistance", target: "Øvre ryg · bagskulder", cue: "Træk mod ansigtet og afslut med skulderbladene samlet", sets: "3", reps: "12", weight: "15" },
  { name: "Straight-arm pulldown", category: "Svømmestyrke", target: "Lats · trækkets afslutning", cue: "Hold armene lange og før hænderne mod lårene", sets: "3", reps: "10", weight: "25" },
  { name: "Single-arm cable pulldown", category: "Svømmestyrke", target: "Lats · ensidig trækkraft", cue: "Træk albuen ned uden at rotere overkroppen", sets: "3", reps: "10", weight: "20" },
  { name: "Swim bench freestyle pull", category: "Svømmestyrke", target: "Crawl · trækkraft på land", cue: "Efterlign et højt albuegreb med rolig kontrol", sets: "4", reps: "8", weight: "10" },
  { name: "Swim bench butterfly pull", category: "Svømmestyrke", target: "Butterfly · symmetrisk trækkraft", cue: "Før begge arme gennem samme bane uden at løfte skuldrene", sets: "4", reps: "8", weight: "10" },
  { name: "Band freestyle stroke", category: "Svømmestyrke", target: "Crawl · rytme · skulderudholdenhed", cue: "Hold kroppen stabil og før én arm ad gangen", sets: "3", reps: "12", weight: "5" },
  { name: "Band butterfly stroke", category: "Svømmestyrke", target: "Butterfly · rytme · lats", cue: "Træk begge arme samtidigt med bløde albuer", sets: "3", reps: "12", weight: "5" },
  { name: "Band breaststroke pull", category: "Svømmestyrke", target: "Brystsvømning · indadføring", cue: "Hold albuerne høje og saml hænderne kontrolleret", sets: "3", reps: "12", weight: "5" },
  { name: "Band backstroke pull", category: "Svømmestyrke", target: "Rygcrawl · bagskulder · lats", cue: "Før armen gennem trækket uden at dreje brystet", sets: "3", reps: "12", weight: "5" },
  { name: "Streamline lat pulldown", category: "Svømmestyrke", target: "Streamline · lats · core", cue: "Start med armene samlet over hovedet og hold ribbenene nede", sets: "3", reps: "10", weight: "25" },
  { name: "Streamline overhead hold", category: "Svømmestyrke", target: "Streamline · skulderstabilitet", cue: "Pres armene sammen og hold en lang kropslinje", sets: "3", reps: "30 sek", weight: "5" },
  { name: "Prone swimmer", category: "Svømmestyrke", target: "Skuldre · øvre ryg · bevægelighed", cue: "Før armene roligt fra streamline til hofterne", sets: "3", reps: "8", weight: "0" },
  { name: "Prone Y-T-W", category: "Svømmestyrke", target: "Skulderblade · rotatorcuff", cue: "Løft armene let uden at spænde i nakken", sets: "3", reps: "6+6+6", weight: "2" },
  { name: "Serratus wall slide", category: "Svømmestyrke", target: "Serratus · skulderkontrol", cue: "Pres underarmene mod væggen og glid kontrolleret op", sets: "3", reps: "10", weight: "0" },
  { name: "Scapular pull-up", category: "Svømmestyrke", target: "Skulderblade · aktivt hæng", cue: "Hold armene lange og sænk skuldrene væk fra ørerne", sets: "3", reps: "8", weight: "0" },
  { name: "Scapular push-up", category: "Svømmestyrke", target: "Serratus · skulderblade", cue: "Hold albuerne strakte og bevæg kun skulderbladene", sets: "3", reps: "12", weight: "0" },
  { name: "Cable internal rotation", category: "Svømmestyrke", target: "Rotatorcuff · indadrotation", cue: "Hold albuen tæt ind til siden og brug let belastning", sets: "3", reps: "12", weight: "5" },
  { name: "Cable external rotation", category: "Svømmestyrke", target: "Rotatorcuff · udadrotation", cue: "Bevar albuen i samme position gennem hele bevægelsen", sets: "3", reps: "12", weight: "5" },
  { name: "Wall angel", category: "Svømmestyrke", target: "Brystryg · skulderbevægelighed", cue: "Hold ribbenene nede og armene tæt på væggen", sets: "3", reps: "10", weight: "0" },
  { name: "Overhead medicine ball throw", category: "Svømmestyrke", target: "Start · vending · eksplosivitet", cue: "Skab kraft fra ben og core før armene afslutter", sets: "5", reps: "4", weight: "4" },
  { name: "Rotational medicine ball throw", category: "Svømmestyrke", target: "Rotation · core · kraftoverførsel", cue: "Drej fra hofterne og hold knæene stabile", sets: "4", reps: "5", weight: "4" },
  { name: "Tall-kneeling cable chop", category: "Svømmestyrke", target: "Core · diagonal kraft", cue: "Hold hofterne stabile mens hænderne føres ned over kroppen", sets: "3", reps: "10", weight: "15" },
  { name: "Tall-kneeling cable lift", category: "Svømmestyrke", target: "Core · skulderkontrol", cue: "Før hænderne diagonalt op uden at svaje i lænden", sets: "3", reps: "10", weight: "12" },
  { name: "Single-arm row with rotation", category: "Svømmestyrke", target: "Træk · kropsrotation", cue: "Træk albuen tilbage og rotér kontrolleret gennem brystryggen", sets: "3", reps: "8", weight: "20" },
  { name: "Isometric catch hold", category: "Svømmestyrke", target: "Greb i vandet · skulderudholdenhed", cue: "Hold høj albue mod elastikkens træk uden at løfte skulderen", sets: "4", reps: "20 sek", weight: "5" },
  { name: "Goblet squat", category: "Assistance", target: "Ben · core · teknik", cue: "Hold vægten tæt ved brystet og knæene stabile", sets: "4", reps: "8", weight: "24" },
  { name: "Trap bar deadlift", category: "Assistance", target: "Ben · bagkæde · greb", cue: "Pres gulvet væk og afslut med hofterne", sets: "4", reps: "5", weight: "100" },
  { name: "Step-up", category: "Assistance", target: "Ensidig benstyrke · stabilitet", cue: "Pres gennem hele foden og undgå afsæt fra bagbenet", sets: "3", reps: "8", weight: "20" },
  { name: "Reverse lunge", category: "Assistance", target: "Ben · balance · hoftekontrol", cue: "Træd roligt tilbage og hold forreste knæ stabilt", sets: "3", reps: "8", weight: "20" },
  { name: "Lateral lunge", category: "Assistance", target: "Hofte · inderlår · sidekraft", cue: "Sæt hoften tilbage over det bøjede ben", sets: "3", reps: "8", weight: "16" },
  { name: "Glute bridge", category: "Assistance", target: "Balder · hofteekstension", cue: "Pres gennem hælene og hold ribbenene nede", sets: "3", reps: "12", weight: "20" },
  { name: "Nordic hamstring curl", category: "Assistance", target: "Baglår · excentrisk styrke", cue: "Sænk kroppen langsomt med hoften strakt", sets: "3", reps: "5", weight: "0" },
  { name: "Lying leg curl", category: "Assistance", target: "Baglår · knækontrol", cue: "Hold hoften i bænken og sænk vægten kontrolleret", sets: "3", reps: "10", weight: "30" },
  { name: "Leg press", category: "Assistance", target: "Ben · generel styrke", cue: "Hold ryggen stabil og arbejd gennem et smertefrit bevægeudslag", sets: "4", reps: "8", weight: "120" },
  { name: "Chest-supported dumbbell row", category: "Assistance", target: "Øvre ryg · lats", cue: "Hold brystet mod bænken og træk albuerne tilbage", sets: "4", reps: "8", weight: "20" },
  { name: "Incline dumbbell bench press", category: "Assistance", target: "Bryst · skuldre · triceps", cue: "Hold skulderbladene stabile og sænk håndvægtene roligt", sets: "4", reps: "8", weight: "20" },
  { name: "Cable chest press", category: "Assistance", target: "Bryst · serratus · core", cue: "Pres frem uden at rotere kroppen", sets: "3", reps: "10", weight: "20" },
  { name: "Landmine row", category: "Assistance", target: "Ryg · greb · bagkæde", cue: "Hold ryggen stabil og træk vægten mod brystet", sets: "4", reps: "8", weight: "40" },
  { name: "Suitcase carry", category: "Assistance", target: "Core · greb · sidestabilitet", cue: "Gå højt uden at læne dig mod vægten", sets: "4", reps: "30 m", weight: "24" },
  { name: "Hollow body hold", category: "Assistance", target: "Core · kropslinje", cue: "Hold lænden mod gulvet og kroppen lang", sets: "3", reps: "30 sek", weight: "0" },
  { name: "Ab wheel rollout", category: "Assistance", target: "Core · anti-ekstension", cue: "Hold bækkenet stabilt og rul kun så langt du kan kontrollere", sets: "3", reps: "8", weight: "0" },
  { name: "Crawl catch-up", category: "Svømning", target: "Crawl · timing", cue: "Lad hænderne mødes foran kroppen før næste armtag", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Crawl med knyttede næver", category: "Svømning", target: "Crawl · vandføling", cue: "Hold høj albue og mærk trykket på underarmen", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Crawl fingertip drag", category: "Svømning", target: "Crawl · afslappet fremføring", cue: "Lad fingerspidserne strejfe vandet med høj albue", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Enarmscrawl", category: "Svømning", target: "Crawl · rotation", cue: "Hold den passive arm fremme og roter fra hoften", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "6-1-6 sideskift", category: "Svømning", target: "Crawl · balance", cue: "Seks benspark på siden, ét armtag og roligt sideskift", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Sculling foran", category: "Svømning", target: "Vandføling · indgreb", cue: "Små bevægelser med albuerne højt og tryk på håndfladen", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Sculling midt", category: "Svømning", target: "Vandføling · trækfase", cue: "Hold overarmene stabile og arbejd med underarmene", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Benspark med plade", category: "Svømning", target: "Ben · udholdenhed", cue: "Små spark fra hoften og afslappede ankler", sets: "6", reps: "25 m", weight: "0", format: "distance" },
  { name: "Sidekick", category: "Svømning", target: "Kropslinje · balance", cue: "Hold kroppen lang og det nederste øre tæt ved armen", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Streamline-benspark på ryggen", category: "Svømning", target: "Streamline · ben", cue: "Klem armene om ørerne og hold hoften højt", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Delfinbenspark på ryggen", category: "Svømning", target: "Undervandsfase · core", cue: "Skab bølgen fra brystkassen og hold knæene samlet", sets: "6", reps: "15 m", weight: "0", format: "distance" },
  { name: "Brystsvømning med glidepause", category: "Svømning", target: "Bryst · timing", cue: "Afslut hvert spark i en lang, rolig streamline", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Brystbenspark med plade", category: "Svømning", target: "Bryst · benspark", cue: "Før hælene roligt op og accelerér fødderne bagud", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Brystarme med pull buoy", category: "Svømning", target: "Bryst · armtag", cue: "Hold trækket kompakt og før hænderne hurtigt frem", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Enarmsrygcrawl", category: "Svømning", target: "Rygcrawl · rotation", cue: "Roter kroppen samlet og hold hovedet roligt", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Rygcrawl 6-kick switch", category: "Svømning", target: "Rygcrawl · balance", cue: "Seks benspark på siden og et kontrolleret armtag", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Butterfly 3-3-3", category: "Svømning", target: "Butterfly · rytme", cue: "Tre tag med hver arm og tre hele tag med samme rytme", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Enarmsbutterfly", category: "Svømning", target: "Butterfly · timing", cue: "Bevar to benspark pr. cyklus og en lav fremføring", sets: "4", reps: "25 m", weight: "0", format: "distance" },
  { name: "Crawl med pull buoy", category: "Svømning", target: "Crawl · armtag", cue: "Hold benene rolige og fasthold et tidligt indgreb", sets: "6", reps: "50 m", weight: "0", format: "distance" },
  { name: "Teknikcrawl med paddles", category: "Svømning", target: "Crawl · greb", cue: "Svøm kontrolleret og stop hvis grebet eller skulderen svigter", sets: "4", reps: "50 m", weight: "0", format: "distance" },
  { name: "Indsvømning", category: "Svømning", target: "Opvarmning · rytme", cue: "Start roligt og øg bevægeudslaget gradvist", sets: "4", reps: "100 m", weight: "0", format: "distance" },
  { name: "Aerob crawl", category: "Svømning", target: "Udholdenhed · pacing", cue: "Hold et tempo du kan gentage med samme teknik", sets: "6", reps: "200 m", weight: "0", format: "distance" },
  { name: "Tærskel crawl", category: "Svømning", target: "Tærskel · fartkontrol", cue: "Svøm kontrolleret hårdt med ensartede splittider", sets: "8", reps: "100 m", weight: "0", format: "distance" },
  { name: "Race pace", category: "Svømning", target: "Konkurrencefart · rytme", cue: "Prioritér præcis fart og teknik frem for ekstra gentagelser", sets: "8", reps: "50 m", weight: "0", format: "distance" },
  { name: "Sprint fra afsæt", category: "Svømning", target: "Acceleration · topfart", cue: "Eksplodér fra væggen og stop før teknikken falder", sets: "8", reps: "25 m", weight: "0", format: "distance" },
  { name: "Startspring og undervand", category: "Svømning", target: "Start · breakout", cue: "Gentag samme opsætning og hold en stram streamline", sets: "8", reps: "15 m", weight: "0", format: "distance" },
  { name: "Vendingstræning", category: "Svømning", target: "Vending · acceleration", cue: "Gå hurtigt ind, roter kompakt og skub i en fast linje", sets: "8", reps: "15 m", weight: "0", format: "distance" },
  { name: "Udsvømning", category: "Svømning", target: "Restitution · bevægelse", cue: "Sænk tempoet og find en rolig vejrtrækning", sets: "4", reps: "100 m", weight: "0", format: "distance" },
];
