export type ExerciseDefinition = {
  name: string;
  category: "Konkurrenceløft" | "Snatch" | "Clean" | "Jerk" | "Squat" | "Træk" | "Assistance";
  target: string;
  cue: string;
  sets: string;
  reps: string;
  weight: string;
};

export const exerciseLibrary: ExerciseDefinition[] = [
  { name: "Snatch", category: "Konkurrenceløft", target: "Helkrop · teknik", cue: "Tæt stang og aktiv modtagelse", sets: "5", reps: "2", weight: "60" },
  { name: "Hang snatch", category: "Snatch", target: "Timing · eksplosivitet", cue: "Hold spændingen over knæet", sets: "4", reps: "3", weight: "50" },
  { name: "Power snatch", category: "Snatch", target: "Hastighed · træk", cue: "Modtag stangen højt og stabilt", sets: "5", reps: "2", weight: "55" },
  { name: "Snatch balance", category: "Snatch", target: "Modtagelse · fodarbejde", cue: "Pres aktivt op mod stangen", sets: "4", reps: "3", weight: "45" },
  { name: "Clean & Jerk", category: "Konkurrenceløft", target: "Helkrop · teknik", cue: "Stabil clean før et roligt dip", sets: "5", reps: "1+1", weight: "80" },
  { name: "Hang clean", category: "Clean", target: "Position · turnover", cue: "Afslut benene før albuerne", sets: "4", reps: "3", weight: "70" },
  { name: "Power clean", category: "Clean", target: "Eksplosivitet · hastighed", cue: "Mød stangen – lad den ikke falde", sets: "5", reps: "2", weight: "75" },
  { name: "Push jerk", category: "Jerk", target: "Ben-drive · timing", cue: "Lodret dip og hurtig lockout", sets: "5", reps: "3", weight: "70" },
  { name: "Front squat", category: "Squat", target: "Ben · core", cue: "Albuer højt gennem hele løftet", sets: "4", reps: "4", weight: "90" },
  { name: "Back squat", category: "Squat", target: "Maksimal benstyrke", cue: "Stabil bracing og ensartet dybde", sets: "5", reps: "5", weight: "110" },
  { name: "Snatch pull", category: "Træk", target: "Ryg · position · kraft", cue: "Bevar skuldrene over stangen", sets: "4", reps: "3", weight: "80" },
  { name: "Clean pull", category: "Træk", target: "Ben · ryg · kraft", cue: "Skub gulvet væk og afslut lodret", sets: "4", reps: "3", weight: "110" },
  { name: "Strict press", category: "Assistance", target: "Skuldre · lockout", cue: "Spænd balder og hold ribben nede", sets: "4", reps: "6", weight: "40" },
  { name: "High hang snatch", category: "Snatch", target: "Timing · hurtighed", cue: "Bliv lodret og angrib under stangen", sets: "5", reps: "2", weight: "45" },
  { name: "Low hang snatch", category: "Snatch", target: "Position · tålmodighed", cue: "Hold rygvinklen til stangen passerer knæet", sets: "4", reps: "3", weight: "50" },
  { name: "Block snatch", category: "Snatch", target: "Eksplosivitet · position", cue: "Skab tryk før du accelererer", sets: "5", reps: "2", weight: "55" },
  { name: "Deficit snatch", category: "Snatch", target: "Startstyrke · ben", cue: "Pres gulvet væk uden at løfte hoften tidligt", sets: "4", reps: "2", weight: "50" },
  { name: "Pause snatch", category: "Snatch", target: "Kontrol · position", cue: "Frys positionen og behold balancen midt på foden", sets: "5", reps: "2", weight: "50" },
  { name: "No-foot snatch", category: "Snatch", target: "Balance · vertikal kraft", cue: "Stræk lodret uden at hoppe frem", sets: "4", reps: "3", weight: "45" },
  { name: "No-hook snatch", category: "Snatch", target: "Afslappede arme · timing", cue: "Lad benene drive løftet", sets: "4", reps: "3", weight: "40" },
  { name: "Muscle snatch", category: "Snatch", target: "Turnover · overkrop", cue: "Hold stangen tæt og afslut med aktive skuldre", sets: "4", reps: "4", weight: "35" },
  { name: "Tall snatch", category: "Snatch", target: "Turnover · hastighed", cue: "Træk dig direkte under stangen", sets: "4", reps: "3", weight: "30" },
  { name: "Snatch from power position", category: "Snatch", target: "Kontakt · timing", cue: "Bevar trykket i hele foden før eksplosiv afslutning", sets: "5", reps: "2", weight: "45" },
  { name: "Snatch from knee", category: "Snatch", target: "Knæpassage · position", cue: "Hold stangen tæt gennem knæpassagen", sets: "4", reps: "3", weight: "50" },
  { name: "Snatch from blocks below knee", category: "Snatch", target: "Første træk · position", cue: "Start roligt og accelerér efter knæet", sets: "4", reps: "2", weight: "55" },
  { name: "Snatch from blocks above knee", category: "Snatch", target: "Andet træk · kraft", cue: "Hold brystet over stangen til kontakt", sets: "5", reps: "2", weight: "55" },
  { name: "Power snatch + overhead squat", category: "Snatch", target: "Modtagelse · mobilitet", cue: "Stabilisér før du går kontrolleret ned", sets: "4", reps: "1+2", weight: "45" },
  { name: "Snatch + overhead squat", category: "Snatch", target: "Stabilitet · teknik", cue: "Behold aktive skuldre mellem løftene", sets: "4", reps: "1+1", weight: "50" },
  { name: "Snatch pull + snatch", category: "Snatch", target: "Trækbane · overførsel", cue: "Gentag samme bane i begge bevægelser", sets: "4", reps: "1+1", weight: "50" },
  { name: "Snatch deadlift", category: "Træk", target: "Position · bagkæde", cue: "Hold brystet over stangen og spænd lats", sets: "4", reps: "4", weight: "90" },
  { name: "Snatch grip RDL", category: "Træk", target: "Baglår · ryg", cue: "Skub hoften tilbage med stangen tæt", sets: "4", reps: "6", weight: "70" },
  { name: "Snatch grip push press", category: "Snatch", target: "Overheadstyrke · timing", cue: "Afslut benene og pres stangen lodret", sets: "4", reps: "5", weight: "45" },
  { name: "Overhead squat", category: "Snatch", target: "Mobilitet · stabilitet", cue: "Pres op i stangen og hold hele foden i gulvet", sets: "4", reps: "5", weight: "45" },
  { name: "High hang clean", category: "Clean", target: "Timing · hurtighed", cue: "Bliv høj og mød stangen hurtigt", sets: "5", reps: "2", weight: "65" },
  { name: "Low hang clean", category: "Clean", target: "Position · kraft", cue: "Hold spændingen under knæet", sets: "4", reps: "3", weight: "70" },
  { name: "Block clean", category: "Clean", target: "Eksplosivitet · turnover", cue: "Skab balance før den eksplosive afslutning", sets: "5", reps: "2", weight: "75" },
  { name: "Deficit clean", category: "Clean", target: "Startstyrke · ben", cue: "Pres jævnt gennem gulvet", sets: "4", reps: "2", weight: "70" },
  { name: "Pause clean", category: "Clean", target: "Kontrol · position", cue: "Bevar spændingen i pausen", sets: "5", reps: "2", weight: "70" },
  { name: "No-foot clean", category: "Clean", target: "Balance · vertikal kraft", cue: "Stræk lodret og land samme sted", sets: "4", reps: "3", weight: "65" },
  { name: "No-hook clean", category: "Clean", target: "Timing · afslappede arme", cue: "Hold armene lange gennem trækket", sets: "4", reps: "3", weight: "60" },
  { name: "Muscle clean", category: "Clean", target: "Turnover · albuer", cue: "Før albuerne hurtigt rundt om stangen", sets: "4", reps: "4", weight: "45" },
  { name: "Tall clean", category: "Clean", target: "Turnover · modtagelse", cue: "Træk kroppen hurtigt ned", sets: "4", reps: "3", weight: "40" },
  { name: "Clean from power position", category: "Clean", target: "Kontakt · timing", cue: "Hold balancen og afslut med benene", sets: "5", reps: "2", weight: "65" },
  { name: "Clean from knee", category: "Clean", target: "Knæpassage · position", cue: "Bevar skuldrene over stangen", sets: "4", reps: "3", weight: "70" },
  { name: "Clean from blocks below knee", category: "Clean", target: "Første træk · styrke", cue: "Pres roligt til stangen passerer knæet", sets: "4", reps: "2", weight: "75" },
  { name: "Clean from blocks above knee", category: "Clean", target: "Andet træk · kraft", cue: "Hold stangen tæt ind i kontakten", sets: "5", reps: "2", weight: "75" },
  { name: "Power clean + front squat", category: "Clean", target: "Modtagelse · benstyrke", cue: "Stabilisér før den kontrollerede squat", sets: "4", reps: "1+2", weight: "70" },
  { name: "Clean + front squat", category: "Clean", target: "Benstyrke · position", cue: "Hold albuerne højt mellem bevægelserne", sets: "4", reps: "1+1", weight: "75" },
  { name: "Clean deadlift", category: "Træk", target: "Position · bagkæde", cue: "Pres gulvet væk med brystet over stangen", sets: "4", reps: "4", weight: "120" },
  { name: "Clean grip RDL", category: "Træk", target: "Baglår · ryg", cue: "Hold lats spændte og hoften tilbage", sets: "4", reps: "6", weight: "90" },
  { name: "Split jerk", category: "Jerk", target: "Fodarbejde · lockout", cue: "Flyt fødderne hurtigt og land stabilt", sets: "5", reps: "2", weight: "75" },
  { name: "Power jerk", category: "Jerk", target: "Ben-drive · modtagelse", cue: "Pres dig hurtigt ned under stangen", sets: "5", reps: "2", weight: "70" },
  { name: "Squat jerk", category: "Jerk", target: "Mobilitet · modtagelse", cue: "Hold dip lodret og modtag aktivt", sets: "4", reps: "2", weight: "55" },
  { name: "Push press", category: "Jerk", target: "Ben-drive · skuldre", cue: "Afslut benene før armene", sets: "4", reps: "5", weight: "60" },
  { name: "Behind-the-neck push press", category: "Jerk", target: "Overheadstyrke · lodret bane", cue: "Hold hovedet neutralt og pres lige op", sets: "4", reps: "5", weight: "65" },
  { name: "Behind-the-neck split jerk", category: "Jerk", target: "Fodarbejde · sikkerhed", cue: "Fokusér på hurtig og balanceret landing", sets: "5", reps: "2", weight: "70" },
  { name: "Jerk from rack", category: "Jerk", target: "Teknik · belastning", cue: "Find balancen før hvert dip", sets: "5", reps: "2", weight: "80" },
  { name: "Jerk from blocks", category: "Jerk", target: "Ben-drive · gentagelser", cue: "Nulstil positionen mellem løftene", sets: "5", reps: "2", weight: "80" },
  { name: "Pause jerk", category: "Jerk", target: "Dipkontrol · timing", cue: "Hold trykket midt på foden i pausen", sets: "5", reps: "2", weight: "70" },
  { name: "Tall jerk", category: "Jerk", target: "Fodarbejde · lockout", cue: "Flyt fødderne uden ekstra dip", sets: "4", reps: "3", weight: "40" },
  { name: "Jerk balance", category: "Jerk", target: "Forreste fod · modtagelse", cue: "Træd frem og lås stangen samtidig", sets: "4", reps: "3", weight: "45" },
  { name: "Press in split", category: "Jerk", target: "Stabilitet · lockout", cue: "Hold hofterne under skuldrene", sets: "4", reps: "5", weight: "35" },
  { name: "Dip squat", category: "Jerk", target: "Dipstyrke · position", cue: "Bevar lodret torso og fuld fodkontakt", sets: "4", reps: "5", weight: "100" },
  { name: "Jerk dip + drive", category: "Jerk", target: "Ben-drive · rytme", cue: "Skift hurtigt retning uden at miste balancen", sets: "4", reps: "3", weight: "85" },
  { name: "Clean & push jerk", category: "Jerk", target: "Helkrop · teknik", cue: "Stabilisér clean før et lodret dip", sets: "5", reps: "1+1", weight: "75" },
  { name: "Pause front squat", category: "Squat", target: "Bundstyrke · position", cue: "Bevar spændingen og albuerne højt", sets: "4", reps: "3", weight: "85" },
  { name: "Tempo front squat", category: "Squat", target: "Kontrol · benstyrke", cue: "Brug tre sekunder ned og rejs dig aggressivt", sets: "4", reps: "4", weight: "75" },
  { name: "Pin front squat", category: "Squat", target: "Startstyrke · core", cue: "Start spændt fra en helt stille position", sets: "5", reps: "3", weight: "80" },
  { name: "Front squat + jerk", category: "Squat", target: "Ben · overførsel", cue: "Brug en stabil squat til at sætte jerken op", sets: "4", reps: "2+1", weight: "75" },
  { name: "Pause back squat", category: "Squat", target: "Bundstyrke · kontrol", cue: "Hold spændingen gennem hele pausen", sets: "4", reps: "4", weight: "95" },
  { name: "Tempo back squat", category: "Squat", target: "Kontrol · muskelstyrke", cue: "Kontrollér vejen ned og behold balancen", sets: "4", reps: "5", weight: "90" },
  { name: "High-bar back squat", category: "Squat", target: "Benstyrke · oprejst position", cue: "Hold knæene fremme og brystet højt", sets: "5", reps: "5", weight: "105" },
  { name: "Low-bar back squat", category: "Squat", target: "Bagkæde · maksimal styrke", cue: "Skab en stabil hylde og pres gennem hoften", sets: "5", reps: "5", weight: "120" },
  { name: "Box squat", category: "Squat", target: "Bagkæde · kontrol", cue: "Sæt dig kontrolleret og behold spændingen", sets: "4", reps: "5", weight: "100" },
  { name: "Anderson squat", category: "Squat", target: "Startstyrke · ben", cue: "Byg spænding før stangen forlader pins", sets: "5", reps: "3", weight: "90" },
  { name: "Split squat", category: "Squat", target: "Ensidig benstyrke · balance", cue: "Hold forreste fod stabil og torso høj", sets: "4", reps: "6", weight: "40" },
  { name: "Bulgarian split squat", category: "Squat", target: "Ensidig styrke · stabilitet", cue: "Sænk bageste knæ kontrolleret", sets: "4", reps: "8", weight: "35" },
  { name: "Snatch high pull", category: "Træk", target: "Kraft · albueføring", cue: "Afslut benene før albuerne går op", sets: "4", reps: "4", weight: "75" },
  { name: "Clean high pull", category: "Træk", target: "Kraft · afslutning", cue: "Hold stangen tæt og afslut lodret", sets: "4", reps: "4", weight: "100" },
  { name: "Snatch pull from blocks", category: "Træk", target: "Andet træk · belastning", cue: "Start balanceret og accelerér gennem kontakten", sets: "4", reps: "3", weight: "85" },
  { name: "Clean pull from blocks", category: "Træk", target: "Andet træk · kraft", cue: "Hold skuldrene over stangen længst muligt", sets: "4", reps: "3", weight: "115" },
  { name: "Snatch pull with pause", category: "Træk", target: "Position · kontrol", cue: "Bevar spændingen i pausen ved knæet", sets: "4", reps: "3", weight: "80" },
  { name: "Clean pull with pause", category: "Træk", target: "Position · benstyrke", cue: "Hold hele foden i gulvet under pausen", sets: "4", reps: "3", weight: "110" },
  { name: "Snatch deficit pull", category: "Træk", target: "Startstyrke · position", cue: "Pres jævnt uden at ændre rygvinklen", sets: "4", reps: "3", weight: "75" },
  { name: "Clean deficit pull", category: "Træk", target: "Startstyrke · ben", cue: "Hold brystet over stangen fra gulvet", sets: "4", reps: "3", weight: "105" },
  { name: "Bench press", category: "Assistance", target: "Bryst · triceps", cue: "Hold skulderbladene stabile mod bænken", sets: "4", reps: "6", weight: "70" },
  { name: "Pendlay row", category: "Assistance", target: "Øvre ryg · trækstyrke", cue: "Hold ryggen fast og træk mod nederste ribben", sets: "4", reps: "6", weight: "70" },
  { name: "Pull-up", category: "Assistance", target: "Ryg · greb", cue: "Start med aktive skuldre og undgå kip", sets: "4", reps: "6", weight: "0" },
  { name: "Romanian deadlift", category: "Assistance", target: "Baglår · bagkæde", cue: "Skub hoften tilbage med neutral ryg", sets: "4", reps: "8", weight: "90" },
  { name: "Plank", category: "Assistance", target: "Core · stabilitet", cue: "Spænd balder og hold ribben nede", sets: "4", reps: "30", weight: "0" },
];
